# Site
name: 'Aayusha Writes'
description: 'Writing and making memories.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/Webp.net-compress-image.jpg'
baseurl: ''
disqus: 'aayushapaudel'
email: 'aayushapaudel.com.np@gmail.com'
google_analytics: 'UA-146879393-1'

mailchimp-list: 'https://gmail.us4.list-manage.com/subscribe/post?u=7be85d3cd92b77ead81c2ac95&amp;id=e416ce24ec'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    Aayusha:
      name:           Aayusha
      site:           https://github.com/Aayusha2055
      avatar:         /assets/images/avatar.jpg
      bio:            "Hi, I am Aayusha, a blogger, who loves to explore people and places and keep writing about it. I hope you like it!"
      email:          aayusha2055@gmail.com
      twitter:        https://twitter.com/aayusha_p
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Aayusha
      avatar: /assets/images/avatar.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]